const assert = require('node:assert/strict');
const sensor = require('../lib/targets.js');
assert.equal(sensor.detectTarget('https://x.com/DefenderOfBasic').id, 'psyop');
assert.equal(sensor.detectTarget('https://rivalvoices.substack.com/').id, 'rivalvoices');
assert.equal(sensor.detectTarget('https://x.com/home'), null);
assert.equal(sensor.parseCompactNumber('1.2K'), 1200);
assert.deepEqual(sensor.extractTweetIdsFromText('https://x.com/DefenderOfBasic/status/1234567890123456789 and /status/42'), ['1234567890123456789']);
const text = '1,234 Followers 88 Following 102 subscribers 12 Replies 34 Reposts 560 Likes 9,876 Views';
const stats = sensor.extractVisibleStats(text, 'https://x.com/DefenderOfBasic');
assert.equal(stats.followers, 1234);
assert.equal(stats.following, 88);
assert.equal(stats.subscribers, 102);
assert.equal(stats.replies, 12);
assert.equal(stats.reposts, 34);
assert.equal(stats.likes, 560);
assert.equal(stats.views, 9876);
const derived = sensor.deriveAttention(stats);
assert.equal(derived.audience, 1234);
assert.equal(derived.interactions, 606);
assert.ok(derived.attention > 700);
console.log('EXTENSION_PARSER_TEST_OK');
